### ISSUE TITLE
Small bug in foreach loops that start with while loops

### ISSUE THREAD

**Issue by Jake-NotTheMuss** [seriousyt/t7-source#2]
When a foreach loop starts with a while loop, some of the compiler-generated code is included in the output. The attached file contains grep results for all instances where "getnextarraykey" is included in the decompiled code at the start of a foreach loop that starts with an inner while loop.
[grep_getnextarraykey.txt](https://github.com/shiversoftdev/t7-source/files/8165334/grep_getnextarraykey.txt)

**Comment by shiversoftdev** [comment]
This is actually due to a 'fix' for prospective for loop detection that was introduced a while back. I incorrectly assumed that all instructions visited in a failed detection needed to be unmarked, but this ended up marking the tail instructions of the foreach pattern as unmarked because foreach loops are processed first in the chain. Gotta love the complexity of this stuff lol. Working on a fix now.
